# Generated by Django 3.1.6 on 2021-06-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jf', '0007_auto_20210602_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsearchfilter',
            name='from_this_company',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
