# Generated by Django 3.1.6 on 2021-06-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jf', '0019_auto_20210602_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsearchfilter',
            name='from_this_company',
            field=models.TextField(blank=True, null=True),
        ),
    ]
