from django.urls import path
from .views import (
    jf_home_view,
    history_list_view,
    history_detail_view,
    history_delete_view,
    history_all_delete_view,
    indeed_search_view,
    history_item_save_view,
    job_save_view,
    job_list_view,
    job_detail_view,
    job_delete_view,
    jobs_all_delete_view,
    filter_jobs_view,
    filter_list_view,
    filter_detail_view,
    filter_delete_view,
    filters_all_delete_view,
)

urlpatterns = [
    path('jf/', jf_home_view, name="jf_home_view"),
    path('jf/history-list', history_list_view),
    path('jf/history-detail/<int:history_id>', history_detail_view),
    path('jf/history-delete/<int:history_id>', history_delete_view),
    path('jf/history-all-delete', history_all_delete_view),
    path('jf/indeed-search', indeed_search_view),
    path('jf/history-item-save/<int:history_id>', history_item_save_view),
    path('jf/job-save', job_save_view, name="job_save_view"),
    path('jf/job-list', job_list_view),
    path('jf/job-detail/<int:job_id>', job_detail_view),
    path('jf/job-delete/<int:job_id>', job_delete_view),
    path('jf/jobs-all-delete', jobs_all_delete_view),
    path('jf/filter-jobs', filter_jobs_view, name="filter_jobs_view"),
    path('jf/filter-list', filter_list_view),
    path('jf/filter-detail/<int:filter_id>', filter_detail_view),
    path('jf/filter-delete/<int:filter_id>', filter_delete_view),
    path('jf/filters-all-delete', filters_all_delete_view),
]
