# Generated by Django 3.1.6 on 2021-03-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeslib', '0003_auto_20210323_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='source',
            field=models.TextField(blank=True, max_length=10240),
        ),
    ]
