# Generated by Django 3.1.6 on 2021-03-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeslib', '0008_auto_20210327_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codelibrary',
            name='title',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
