# Generated by Django 3.1.6 on 2021-03-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeslib', '0009_auto_20210327_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codelibrary',
            name='is_favorite',
            field=models.BooleanField(null=True),
        ),
    ]
