# Generated by Django 3.1.6 on 2021-03-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeslib', '0014_auto_20210327_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codelibrary',
            name='is_favorite',
            field=models.BooleanField(default=True),
        ),
    ]
