# Generated by Django 3.1.6 on 2021-03-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeslib', '0016_auto_20210327_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codelibrary',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
